#!/usr/bin/env bash
#
# Build the agora_rs native library for Android (arm64-v8a).
#
# Prerequisites:
#   1. Rust toolchain with Android target:
#        rustup target add aarch64-linux-android
#   2. cargo-ndk:
#        cargo install cargo-ndk
#   3. Android NDK (matched to build.gradle.kts: ndkVersion = "28.2.13676358")
#      Installed via Android Studio SDK Manager or sdkmanager CLI.
#   4. ANDROID_NDK_HOME environment variable set to the NDK installation path.
#
# Usage:
#   cd rust-core && bash build-android.sh
#
# Output: ../app/src/main/jniLibs/arm64-v8a/libagora_rs.so

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
JNI_LIBS_DIR="${PROJECT_DIR}/app/src/main/jniLibs"
TARGET_ARCH="arm64-v8a"
RUST_TARGET="aarch64-linux-android"

# Detect NDK
if [ -z "${ANDROID_NDK_HOME:-}" ]; then
    # Try to locate from common SDK locations
    if [ -d "$HOME/Android/Sdk/ndk" ]; then
        ANDROID_NDK_HOME=$(ls -d "$HOME/Android/Sdk/ndk"/*/ 2>/dev/null | sort -V | tail -1)
    elif [ -d "$HOME/Library/Android/sdk/ndk" ]; then
        ANDROID_NDK_HOME=$(ls -d "$HOME/Library/Android/sdk/ndk"/*/ 2>/dev/null | sort -V | tail -1)
    elif [ -d "/usr/local/lib/android/sdk/ndk" ]; then
        ANDROID_NDK_HOME=$(ls -d "/usr/local/lib/android/sdk/ndk"/*/ 2>/dev/null | sort -V | tail -1)
    fi
    if [ -z "${ANDROID_NDK_HOME:-}" ] || [ ! -d "$ANDROID_NDK_HOME" ]; then
        echo "ERROR: Cannot find Android NDK. Set ANDROID_NDK_HOME or install via SDK Manager."
        exit 1
    fi
fi

echo "Using NDK: ${ANDROID_NDK_HOME}"

# Create .cargo/config.toml for the NDK linker if not present
CARGO_CONFIG="${SCRIPT_DIR}/.cargo/config.toml"
mkdir -p "$(dirname "${CARGO_CONFIG}")"

if [ ! -f "${CARGO_CONFIG}" ]; then
    LLVM_BIN="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin"
    if [ "$(uname)" = "Darwin" ]; then
        LLVM_BIN="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/darwin-x86_64/bin"
    fi

    cat > "${CARGO_CONFIG}" <<CONFIGEOF
# Auto-generated by build-android.sh
# See https://developer.android.com/ndk/guides/other_build_systems#rust

[target.aarch64-linux-android]
linker = "${LLVM_BIN}/aarch64-linux-android21-clang"

[target.armv7-linux-androideabi]
linker = "${LLVM_BIN}/armv7a-linux-androideabi21-clang"

[target.x86_64-linux-android]
linker = "${LLVM_BIN}/x86_64-linux-android21-clang"

[target.i686-linux-android]
linker = "${LLVM_BIN}/i686-linux-android21-clang"
CONFIGEOF
    echo "Created ${CARGO_CONFIG}"
fi

# Build
echo "Building ${RUST_TARGET} (release)..."
cargo ndk \
    --target "${TARGET_ARCH}" \
    --platform 24 \
    --output-dir "${JNI_LIBS_DIR}" \
    build --release

echo "Done! Output: ${JNI_LIBS_DIR}/${TARGET_ARCH}/libagora_rs.so"
ls -lh "${JNI_LIBS_DIR}/${TARGET_ARCH}/libagora_rs.so" 2>/dev/null || echo "(check output directory)"